/* ============================================================
   GOLDEN BANKER — DATA FETCHER  (API-Football / api-sports.io)
   Runs on YOUR PC. Pulls today's fixtures + standings, keeps
   history, and writes data.js for your website.

   You do NOT edit this file. Use set-key.bat to set your key,
   edit config.txt for leagues, then double-click run-fetch.bat.
   ============================================================ */

const fs = require("fs");
const path = require("path");
const https = require("https");
const HERE = __dirname;

function readConfig() {
  const raw = fs.readFileSync(path.join(HERE, "config.txt"), "utf8");
  const cfg = { API_KEY: "", SEASON: "", LEAGUES: [] };
  for (let line of raw.split(/\r?\n/)) {
    line = line.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim().toUpperCase();
    const val = line.slice(eq + 1).trim();
    if (key === "API_KEY") cfg.API_KEY = val.replace(/['"*]/g, "").replace(/[^A-Za-z0-9\-]/g, "");
    else if (key === "SEASON") cfg.SEASON = val.replace(/[^0-9]/g, "");
    else if (key === "LEAGUES") cfg.LEAGUES = val.split(",").map(s => s.trim()).filter(Boolean).map(s => parseInt(s,10)).filter(n=>!isNaN(n));
  }
  return cfg;
}

function apiGet(endpoint, key) {
  return new Promise((resolve, reject) => {
    const opts = { method:"GET", hostname:"v3.football.api-sports.io", path:endpoint, headers:{ "x-apisports-key":key } };
    const req = https.request(opts, res => {
      let body = "";
      res.on("data", d => (body += d));
      res.on("end", () => {
        if (res.statusCode === 429) { reject(new Error("RATE_LIMIT")); return; }
        try {
          const json = JSON.parse(body);
          if (json.errors && !Array.isArray(json.errors) && Object.keys(json.errors).length) {
            reject(new Error("API_ERROR: " + Object.values(json.errors).join("; "))); return;
          }
          resolve(json);
        } catch (e) { reject(new Error("Bad JSON from " + endpoint)); }
      });
    });
    req.on("error", reject);
    req.end();
  });
}

function todayStr(){ const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }
const sleep = ms => new Promise(r=>setTimeout(r,ms));
function round1(n){ return Math.round(n*10)/10; }
function cleanForm(f){ if(!f) return "—"; const s=String(f).replace(/[^WDL]/gi,"").toUpperCase(); return s?s.slice(-5):"—"; }
const FINISHED = new Set(["FT","AET","PEN"]);

(async () => {
  console.log("\n=== Golden Banker data fetcher (API-Football) ===\n");
  let cfg;
  try { cfg = readConfig(); }
  catch (e) { console.log("ERROR: could not read config.txt — is it next to this file?"); process.exit(1); }

  const placeholder = "PASTE_YOUR_KEY_HERE".replace(/[^A-Za-z0-9]/g,"");
  if (!cfg.API_KEY || cfg.API_KEY === placeholder) { console.log("ERROR: set your key first — double-click set-key.bat."); process.exit(1); }
  if (!cfg.LEAGUES.length) { console.log("ERROR: add league IDs in config.txt (e.g. LEAGUES=1,39,140)."); process.exit(1); }

  const season = cfg.SEASON || String(new Date().getFullYear());
  const date = todayStr();
  const k = cfg.API_KEY;
  console.log(`Token read: ${k.length<=8?k:k.slice(0,4)+"…"+k.slice(-4)}  (length ${k.length})`);
  console.log(`Date: ${date}   Season: ${season}   Leagues: ${cfg.LEAGUES.join(", ")}\n`);

  const out = [];
  let requests = 0, firstError = null;

  for (const leagueId of cfg.LEAGUES) {
    // Try the configured season first; if no fixtures, try the adjacent
    // season year. This covers BOTH the World Cup (2026) and domestic
    // leagues (2025/26 -> season 2025) from one config, automatically.
    const seasonsToTry = [season, String(parseInt(season,10)-1)];
    let fixtures = [], usedSeason = season, fxOk = false;
    for (const s of seasonsToTry) {
      try {
        const fxRes = await apiGet(`/fixtures?league=${leagueId}&season=${s}&date=${date}`, cfg.API_KEY);
        requests++; fxOk = true;
        const arr = fxRes.response || [];
        if (arr.length) { fixtures = arr; usedSeason = s; break; }
      } catch (e) {
        if (e.message === "RATE_LIMIT") { console.log("RATE LIMIT — wait a minute and run again."); fixtures=[]; break; }
        if (!firstError) firstError = e.message;
        // season-access errors are expected for the wrong year on free plans
      }
      await sleep(6500);
    }
    if (!fxOk && !fixtures.length) { console.log(`League ${leagueId}: skipped`); await sleep(6500); continue; }
    if (!fixtures.length) { console.log(`League ${leagueId}: no fixtures today`); await sleep(6500); continue; }
    const season_for_standings = usedSeason;

    let table = {}, tableSize = 20, leagueName = `League ${leagueId}`;
    try {
      const stRes = await apiGet(`/standings?league=${leagueId}&season=${season_for_standings}`, cfg.API_KEY); requests++;
      const block = stRes.response && stRes.response[0];
      if (block) {
        leagueName = block.league.name;
        const groups = block.league.standings || [];
        let count = 0;
        for (const g of groups) for (const row of g) { table[row.team.id] = row; count++; }
        tableSize = groups.length === 1 ? groups[0].length : count;
      }
    } catch (e) { console.log(`League ${leagueId}: no standings (${e.message}) — neutral stats`); }
    if (fixtures[0].league && fixtures[0].league.name) leagueName = fixtures[0].league.name;

    for (const fx of fixtures) {
      const st = fx.fixture.status.short;
      const H = table[fx.teams.home.id] || {}, A = table[fx.teams.away.id] || {};
      const hHome = H.home || {}, aAway = A.away || {};
      const played = FINISHED.has(st);
      out.push({
        home: fx.teams.home.name, away: fx.teams.away.name, league: leagueName,
        status: st, kickoff: fx.fixture.date || null, matchDate: date,
        homeGoals: (fx.goals && fx.goals.home != null) ? fx.goals.home : null,
        awayGoals: (fx.goals && fx.goals.away != null) ? fx.goals.away : null,
        homePos: H.rank ?? null, awayPos: A.rank ?? null, tableSize,
        homePts: H.points ?? 0, awayPts: A.points ?? 0,
        homeGD: H.goalsDiff ?? 0, awayGD: A.goalsDiff ?? 0,
        homeForm: cleanForm(H.form), awayForm: cleanForm(A.form),
        homeScoredAtHome: round1(hHome.played ? hHome.goals.for/hHome.played : 1.3),
        homeConcededAtHome: round1(hHome.played ? hHome.goals.against/hHome.played : 1.1),
        awayScoredAway: round1(aAway.played ? aAway.goals.for/aAway.played : 1.0),
        awayConcededAway: round1(aAway.played ? aAway.goals.against/aAway.played : 1.4),
      });
      console.log(`  + ${fx.teams.home.name} vs ${fx.teams.away.name}${played?` (${fx.goals.home}-${fx.goals.away} FT)`:""}  [${leagueName}]`);
    }
    await sleep(6500);
  }

  if (!out.length) {
    if (firstError) {
      console.log("\nNo matches saved. First issue: " + firstError);
      if (firstError.includes("season")) console.log("If it mentions the season, your plan may not cover it. Pro unlocks current seasons.");
    } else {
      console.log("\nNo fixtures today in your leagues (off-season is normal in summer).");
      console.log("The World Cup is league ID 1 — make sure it's in config.txt.");
    }
    console.log("Leaving your existing data.js untouched (not overwriting with empty).\n");
    return;
  }

  let existing = [];
  try {
    const prev = fs.readFileSync(path.join(HERE, "data.js"), "utf8");
    const m = prev.match(/window\.MATCHES\s*=\s*(\[[\s\S]*\]);?\s*$/);
    if (m) existing = JSON.parse(m[1]);
  } catch (e) {}
  const kept = existing.filter(x => x.matchDate && x.matchDate !== date);
  const merged = kept.concat(out);
  merged.sort((a,b)=>{ if(a.matchDate!==b.matchDate) return (b.matchDate||"").localeCompare(a.matchDate||""); return (a.kickoff||"").localeCompare(b.kickoff||""); });

  fs.writeFileSync(path.join(HERE, "data.js"),
    "/* AUTO-GENERATED by fetch-data.js on " + new Date().toLocaleString() + " — do not edit by hand. */\n\n" +
    "window.MATCHES = " + JSON.stringify(merged, null, 2) + ";\n", "utf8");

  const finishedToday = out.filter(x=>x.homeGoals!=null).length;
  console.log(`\nDone. Today: ${out.length} match(es) (${finishedToday} finished). ${requests} requests used.`);
  console.log(`Board now holds ${merged.length} match(es) across all saved days.`);
  console.log("Next: drag your banker-app folder to app.netlify.com/drop to update the site.\n");
})();
