/* Predict2U v200 — PWA registration, install/update UX, network recovery and deep-link readiness */
(function(){
  'use strict';
  const VERSION='v200', SW='sw.js', DISMISS_KEY='p2u_app_prompt_dismissed_v200';
  let deferredInstall=null, registration=null, reloading=false;
  const $=(s,r=document)=>r.querySelector(s);
  const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
  const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
  const safeText=v=>String(v==null?'':v).slice(0,240);
  const cssEscape=v=>(window.CSS&&CSS.escape?CSS.escape(String(v)):String(v).replace(/[^a-zA-Z0-9_-]/g,'\\$&'));

  function setMode(){document.documentElement.classList.toggle('p2u-standalone',standalone());document.documentElement.dataset.p2uAppMode=standalone()?'standalone':'browser'}
  function networkPill(){let el=$('.p2u-network-state');if(!el){el=document.createElement('div');el.className='p2u-network-state';el.setAttribute('role','status');el.setAttribute('aria-live','polite');document.body.appendChild(el)}return el}
  function showNetwork(online){const el=networkPill();el.textContent=online?'Back online — syncing updates':'Offline mode — saved pages remain available';el.className='p2u-network-state is-show '+(online?'is-online':'is-offline');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('is-show'),online?2600:5200);document.documentElement.dataset.p2uOnline=online?'true':'false';window.dispatchEvent(new CustomEvent('p2u:network',{detail:{online}}));if(online)flushOutbox()}

  function appBanner({kind='info',title,copy,primary,secondary,onPrimary,onSecondary}){let el=$('.p2u-app-banner');if(!el){el=document.createElement('aside');el.className='p2u-app-banner';el.setAttribute('role','status');el.setAttribute('aria-live','polite');document.body.appendChild(el)}el.innerHTML='<div class="p2u-app-banner__icon" aria-hidden="true">P</div><div class="p2u-app-banner__copy"><strong></strong><span></span></div><div class="p2u-app-banner__actions"></div>';$('strong',el).textContent=safeText(title);$('span',el).textContent=safeText(copy);const actions=$('.p2u-app-banner__actions',el);if(primary){const b=document.createElement('button');b.type='button';b.dataset.primary='';b.textContent=primary;b.onclick=()=>{onPrimary&&onPrimary();};actions.appendChild(b)}if(secondary){const b=document.createElement('button');b.type='button';b.textContent=secondary;b.onclick=()=>{onSecondary?onSecondary():hideBanner()};actions.appendChild(b)}el.dataset.kind=kind;requestAnimationFrame(()=>el.classList.add('is-show'));return el}
  function hideBanner(){const el=$('.p2u-app-banner');if(el)el.classList.remove('is-show')}

  async function promptInstall(){if(deferredInstall){deferredInstall.prompt();const choice=await deferredInstall.userChoice.catch(()=>({outcome:'dismissed'}));deferredInstall=null;hideBanner();window.dispatchEvent(new CustomEvent('p2u:install-choice',{detail:choice}));return choice}if(isIOS()&&!standalone()){showIOSGuide();return{outcome:'instructions'}}return{outcome:'unavailable'}}
  function showIOSGuide(){let ov=$('.p2u-install-guide');if(!ov){ov=document.createElement('div');ov.className='p2u-install-guide';ov.innerHTML='<section class="p2u-install-guide__card" role="dialog" aria-modal="true" aria-labelledby="p2u-install-title"><h2 id="p2u-install-title">Install Predict2U</h2><p>On iPhone or iPad:</p><ol><li>Tap the Share button in Safari.</li><li>Choose <strong>Add to Home Screen</strong>.</li><li>Tap <strong>Add</strong>.</li></ol><button type="button">Done</button></section>';document.body.appendChild(ov);ov.addEventListener('click',e=>{if(e.target===ov||e.target.closest('button'))ov.classList.remove('is-open')})}ov.classList.add('is-open')}
  function maybeOfferInstall(){if(standalone()||sessionStorage.getItem(DISMISS_KEY))return;appBanner({kind:'install',title:'Install Predict2U',copy:'Faster opening, offline shell, push deep links and home-screen access.',primary:'Install',secondary:'Not now',onPrimary:promptInstall,onSecondary:()=>{sessionStorage.setItem(DISMISS_KEY,'1');hideBanner()}})}

  function announceUpdate(worker){appBanner({kind:'update',title:'A new Predict2U version is ready',copy:'Update now to load the newest Board, News and app improvements.',primary:'Update now',secondary:'Later',onPrimary:()=>{if(worker)worker.postMessage('SKIP_WAITING');else registration&&registration.waiting&&registration.waiting.postMessage('SKIP_WAITING')}})}
  async function register(){if(!('serviceWorker'in navigator))return null;try{registration=await navigator.serviceWorker.register(SW,{scope:'./',updateViaCache:'none'});registration.update().catch(()=>{});if(registration.waiting&&navigator.serviceWorker.controller)announceUpdate(registration.waiting);registration.addEventListener('updatefound',()=>{const nw=registration.installing;if(!nw)return;nw.addEventListener('statechange',()=>{if(nw.state==='installed'&&navigator.serviceWorker.controller)announceUpdate(nw)})});return registration}catch(err){console.warn('Predict2U app worker unavailable',err);return null}}

  function sanitizeDeepLink(){const u=new URL(location.href);const allowed=['match','story','post','proof','tab'];const detail={};for(const key of allowed){const value=u.searchParams.get(key);if(value)detail[key]=value.slice(0,160)}if(Object.keys(detail).length){window.dispatchEvent(new CustomEvent('p2u:deep-link',{detail}));setTimeout(()=>{const id=detail.story||detail.post||detail.match;const escaped=cssEscape(id||'');const target=id&&document.querySelector(`[data-story-id="${escaped}"],[data-slip-id="${escaped}"],[data-p2u-match-key="${escaped}"],#${escaped}`);if(target)target.scrollIntoView({block:'center',behavior:'smooth'})},1000)}}
  function warmPages(){if(!navigator.serviceWorker.controller)return;const current=location.pathname.split('/').pop()||'index.html';const map={'index.html':['board.html','news.html'],'board.html':['proof.html','community.html'],'news.html':['community.html','account.html'],'community.html':['news.html','account.html'],'proof.html':['board.html','scorecards.html']};navigator.serviceWorker.controller.postMessage({type:'PREFETCH_URLS',urls:map[current]||['index.html','board.html','news.html']})}

  function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('p2u-app-v200',1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('outbox'))db.createObjectStore('outbox',{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
  async function enqueue(action){const item={id:(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()),kind:safeText(action&&action.kind||'action'),payload:action&&action.payload||{},createdAt:new Date().toISOString(),attempts:0};const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction('outbox','readwrite');tx.objectStore('outbox').put(item);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});if(registration&&registration.sync)registration.sync.register('p2u-sync-outbox').catch(()=>{});window.dispatchEvent(new CustomEvent('p2u:outbox-queued',{detail:item}));return item}
  async function readOutbox(){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('outbox','readonly');const req=tx.objectStore('outbox').getAll();req.onsuccess=()=>res(req.result||[]);req.onerror=()=>rej(req.error)})}
  async function removeOutbox(id){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('outbox','readwrite');tx.objectStore('outbox').delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
  async function flushOutbox(){if(!navigator.onLine)return;const items=await readOutbox().catch(()=>[]);let completed=0;for(const item of items){let finish;const acknowledged=new Promise(resolve=>{finish=resolve});const event=new CustomEvent('p2u:offline-action',{detail:{item,complete:()=>finish(true)}});window.dispatchEvent(event);const handled=await Promise.race([acknowledged,new Promise(resolve=>setTimeout(()=>resolve(false),8000))]);if(handled){await removeOutbox(item.id).catch(()=>{});completed+=1}}if(items.length)window.dispatchEvent(new CustomEvent('p2u:outbox-flush',{detail:{count:items.length,completed}}))}

  async function setBadge(count){if(!('setAppBadge'in navigator))return false;try{if(Number(count)>0)await navigator.setAppBadge(Number(count));else if('clearAppBadge'in navigator)await navigator.clearAppBadge();return true}catch(_){return false}}
  function connectPushBadge(){let count=Number(localStorage.getItem('p2u_unread_push_v200')||0);setBadge(count);navigator.serviceWorker&&navigator.serviceWorker.addEventListener('message',e=>{if(e.data&&e.data.type==='P2U_PUSH_RECEIVED'){count+=1;localStorage.setItem('p2u_unread_push_v200',String(count));setBadge(count)}if(e.data&&e.data.type==='P2U_FLUSH_OUTBOX')flushOutbox()});window.addEventListener('p2u:notifications-opened',()=>{count=0;localStorage.setItem('p2u_unread_push_v200','0');setBadge(0)})}

  function init(){setMode();window.addEventListener('online',()=>showNetwork(true));window.addEventListener('offline',()=>showNetwork(false));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;setTimeout(maybeOfferInstall,800)});window.addEventListener('appinstalled',()=>{hideBanner();setMode();window.dispatchEvent(new CustomEvent('p2u:installed'))});navigator.serviceWorker&&navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()});register().then(()=>{warmPages();flushOutbox()});sanitizeDeepLink();connectPushBadge();if(isIOS()&&!standalone()&&!sessionStorage.getItem(DISMISS_KEY))setTimeout(maybeOfferInstall,1800);window.P2UPWA={version:VERSION,register,promptInstall,showIOSGuide,setBadge,enqueue,flushOutbox,getRegistration:()=>registration,isStandalone:standalone,clearRuntimeCaches:()=>navigator.serviceWorker.controller&&navigator.serviceWorker.controller.postMessage({type:'CLEAR_RUNTIME_CACHES'})};document.documentElement.dataset.p2uPwaReady='true';window.dispatchEvent(new CustomEvent('p2u:pwa-ready',{detail:{version:VERSION,standalone:standalone()}}))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
