-- Predict2U v186 — Privacy-First Analytics & Product Intelligence
-- Run in the SAME Supabase project used by v180-v183.
-- Stores product events without raw IP addresses, full user agents, emails,
-- payment data, bookmaker credentials, or advertising identifiers.

begin;

create table if not exists public.p2u_analytics_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  event_name text not null,
  occurred_at timestamptz not null default now(),
  received_at timestamptz not null default now(),
  page_path text not null default '/',
  session_id text not null,
  user_id uuid null references auth.users(id) on delete set null,
  device_class text not null default 'unknown',
  viewport_bucket text not null default 'unknown',
  network_class text not null default 'unknown',
  referrer_host text not null default '',
  installed boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  constraint p2u_analytics_event_name_length check (char_length(event_name) between 2 and 64),
  constraint p2u_analytics_session_length check (char_length(session_id) between 8 and 80)
);

create index if not exists p2u_analytics_events_time_idx
  on public.p2u_analytics_events(occurred_at desc);
create index if not exists p2u_analytics_events_name_time_idx
  on public.p2u_analytics_events(event_name, occurred_at desc);
create index if not exists p2u_analytics_events_page_time_idx
  on public.p2u_analytics_events(page_path, occurred_at desc);
create index if not exists p2u_analytics_events_session_time_idx
  on public.p2u_analytics_events(session_id, occurred_at desc);
create index if not exists p2u_analytics_events_user_time_idx
  on public.p2u_analytics_events(user_id, occurred_at desc)
  where user_id is not null;

alter table public.p2u_analytics_events enable row level security;

-- No direct browser reads or writes. Events enter only through a validated RPC.
revoke all on table public.p2u_analytics_events from anon, authenticated;

create or replace function public.p2u_ingest_analytics_events(p_events jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  item jsonb;
  clean_name text;
  clean_session text;
  clean_page text;
  clean_device text;
  clean_viewport text;
  clean_network text;
  clean_referrer text;
  clean_metadata jsonb;
  clean_time timestamptz;
  accepted integer := 0;
  ignored integer := 0;
  allowed_names constant text[] := array[
    'page_view','navigation','search_used','filter_changed','match_opened','league_opened','engine_opened',
    'record_saved','slip_added','share_opened','share_completed','community_opened','community_posted',
    'follow_changed','personalization_opened','alert_center_opened','push_enabled','install_prompt_shown',
    'install_completed','account_sync','web_vital','client_error'
  ];
begin
  if jsonb_typeof(p_events) <> 'array' then
    raise exception 'p_events must be a JSON array' using errcode = '22023';
  end if;

  if jsonb_array_length(p_events) > 50 then
    raise exception 'A maximum of 50 events is allowed per request' using errcode = '22023';
  end if;

  for item in select value from jsonb_array_elements(p_events)
  loop
    clean_name := lower(left(trim(coalesce(item->>'event_name','')),64));
    clean_session := left(regexp_replace(trim(coalesce(item->>'session_id','')), '[^A-Za-z0-9_-]', '', 'g'),80);
    clean_page := left(regexp_replace(coalesce(item->>'page_path','/'), '[\r\n\t]', '', 'g'),180);
    clean_device := case when lower(item->>'device_class') in ('mobile','tablet','desktop') then lower(item->>'device_class') else 'unknown' end;
    clean_viewport := left(regexp_replace(coalesce(item->>'viewport_bucket','unknown'), '[^A-Za-z0-9._-]', '', 'g'),40);
    clean_network := left(regexp_replace(coalesce(item->>'network_class','unknown'), '[^A-Za-z0-9._-]', '', 'g'),20);
    clean_referrer := left(regexp_replace(lower(coalesce(item->>'referrer_host','')), '[^a-z0-9.-]', '', 'g'),120);

    if clean_name <> all(allowed_names) or char_length(clean_session) < 8 then
      ignored := ignored + 1;
      continue;
    end if;

    begin
      clean_time := (item->>'occurred_at')::timestamptz;
    exception when others then
      clean_time := now();
    end;
    if clean_time > now() + interval '5 minutes' or clean_time < now() - interval '7 days' then
      clean_time := now();
    end if;

    clean_metadata := jsonb_strip_nulls(jsonb_build_object(
      'source', left(coalesce(item->'metadata'->>'source',''),120),
      'action', left(coalesce(item->'metadata'->>'action',''),120),
      'view', left(coalesce(item->'metadata'->>'view',''),120),
      'category', left(coalesce(item->'metadata'->>'category',''),120),
      'entityType', left(coalesce(item->'metadata'->>'entityType',''),80),
      'entityKey', left(coalesce(item->'metadata'->>'entityKey',''),180),
      'league', left(coalesce(item->'metadata'->>'league',''),120),
      'engine', left(coalesce(item->'metadata'->>'engine',''),80),
      'status', left(coalesce(item->'metadata'->>'status',''),80),
      'target', left(coalesce(item->'metadata'->>'target',''),120),
      'name', left(coalesce(item->'metadata'->>'name',''),80),
      'value', case when jsonb_typeof(item->'metadata'->'value') = 'number' then item->'metadata'->'value' else to_jsonb(left(coalesce(item->'metadata'->>'value',''),80)) end,
      'rating', left(coalesce(item->'metadata'->>'rating',''),40),
      'delta', case when jsonb_typeof(item->'metadata'->'delta') = 'number' then item->'metadata'->'delta' else null end,
      'count', case when jsonb_typeof(item->'metadata'->'count') = 'number' then item->'metadata'->'count' else null end,
      'method', left(coalesce(item->'metadata'->>'method',''),40),
      'result', left(coalesce(item->'metadata'->>'result',''),80),
      'reason', left(coalesce(item->'metadata'->>'reason',''),120)
    ));

    insert into public.p2u_analytics_events(
      event_id,event_name,occurred_at,page_path,session_id,user_id,
      device_class,viewport_bucket,network_class,referrer_host,installed,metadata
    ) values (
      coalesce(nullif(item->>'event_id','')::uuid,gen_random_uuid()),
      clean_name,
      clean_time,
      case when clean_page like '/%' then clean_page else '/' || clean_page end,
      clean_session,
      auth.uid(),
      clean_device,
      clean_viewport,
      clean_network,
      clean_referrer,
      coalesce((item->>'installed')::boolean,false),
      clean_metadata
    ) on conflict(event_id) do nothing;

    if found then accepted := accepted + 1; else ignored := ignored + 1; end if;
  end loop;

  return jsonb_build_object('ok',true,'accepted',accepted,'ignored',ignored,'version','v186');
end;
$$;

revoke all on function public.p2u_ingest_analytics_events(jsonb) from public;
grant execute on function public.p2u_ingest_analytics_events(jsonb) to anon, authenticated;

create or replace function public.p2u_admin_analytics_overview(p_days integer default 30)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  clean_days integer := greatest(1,least(coalesce(p_days,30),365));
  since_time timestamptz;
  result jsonb;
begin
  if not public.p2u_has_admin_role(array['owner','admin','moderator']) then
    raise exception 'Admin role required' using errcode='42501';
  end if;

  since_time := date_trunc('day',now()) - make_interval(days => clean_days - 1);

  with base as (
    select * from public.p2u_analytics_events where occurred_at >= since_time
  ),
  session_stats as (
    select
      count(distinct session_id)::integer as sessions,
      count(*) filter(where event_name='page_view')::integer as page_views,
      count(*) filter(where event_name<>'page_view')::integer as interactions,
      count(*) filter(where event_name='client_error')::integer as client_errors,
      count(*) filter(where event_name='push_enabled')::integer as push_enabled,
      count(distinct session_id) filter(where event_name not in ('page_view','web_vital'))::integer as engaged_sessions
    from base
  ),
  top_pages as (
    select coalesce(jsonb_agg(to_jsonb(x) order by x.count desc),'[]'::jsonb) value
    from (
      select page_path,count(*)::integer as count
      from base where event_name='page_view'
      group by page_path order by count(*) desc limit 12
    ) x
  ),
  top_events as (
    select coalesce(jsonb_agg(to_jsonb(x) order by x.count desc),'[]'::jsonb) value
    from (
      select event_name,count(*)::integer as count
      from base where event_name not in ('page_view','web_vital')
      group by event_name order by count(*) desc limit 14
    ) x
  ),
  top_entities as (
    select coalesce(jsonb_agg(to_jsonb(x) order by x.count desc),'[]'::jsonb) value
    from (
      select
        nullif(metadata->>'entityType','') as entity_type,
        nullif(metadata->>'entityKey','') as entity_key,
        count(*)::integer as count
      from base
      where nullif(metadata->>'entityType','') is not null
        and nullif(metadata->>'entityKey','') is not null
      group by 1,2 order by count(*) desc limit 16
    ) x
  ),
  daily as (
    select coalesce(jsonb_agg(to_jsonb(x) order by x.day),'[]'::jsonb) value
    from (
      select to_char(d.day,'YYYY-MM-DD') as day,
             count(b.id) filter(where b.event_name='page_view')::integer as page_views,
             count(distinct b.session_id)::integer as sessions,
             count(b.id) filter(where b.event_name<>'page_view')::integer as interactions
      from generate_series(date_trunc('day',since_time),date_trunc('day',now()),interval '1 day') d(day)
      left join base b on b.occurred_at >= d.day and b.occurred_at < d.day + interval '1 day'
      group by d.day
    ) x
  ),
  device_mix as (
    select coalesce(jsonb_agg(to_jsonb(x) order by x.sessions desc),'[]'::jsonb) value
    from (
      select device_class,count(distinct session_id)::integer as sessions,
             round(100.0*count(distinct session_id)/nullif((select count(distinct session_id) from base),0),1) as share_pct
      from base group by device_class
    ) x
  ),
  vital_rows as (
    select metadata->>'name' as name,
           percentile_cont(0.75) within group(order by (metadata->>'value')::numeric) as p75
    from base
    where event_name='web_vital'
      and metadata->>'name' in ('LCP','INP','CLS','FCP')
      and metadata->>'value' ~ '^[0-9]+(\.[0-9]+)?$'
    group by metadata->>'name'
  ),
  vitals as (
    select jsonb_build_object(
      'lcp_p75',max(p75) filter(where name='LCP'),
      'lcp_rating',case when max(p75) filter(where name='LCP') is null then null when max(p75) filter(where name='LCP') <=2500 then 'Good' when max(p75) filter(where name='LCP') <=4000 then 'Needs improvement' else 'Poor' end,
      'inp_p75',max(p75) filter(where name='INP'),
      'inp_rating',case when max(p75) filter(where name='INP') is null then null when max(p75) filter(where name='INP') <=200 then 'Good' when max(p75) filter(where name='INP') <=500 then 'Needs improvement' else 'Poor' end,
      'cls_p75',max(p75) filter(where name='CLS'),
      'cls_rating',case when max(p75) filter(where name='CLS') is null then null when max(p75) filter(where name='CLS') <=0.1 then 'Good' when max(p75) filter(where name='CLS') <=0.25 then 'Needs improvement' else 'Poor' end,
      'fcp_p75',max(p75) filter(where name='FCP'),
      'fcp_rating',case when max(p75) filter(where name='FCP') is null then null when max(p75) filter(where name='FCP') <=1800 then 'Good' when max(p75) filter(where name='FCP') <=3000 then 'Needs improvement' else 'Poor' end
    ) value from vital_rows
  ),
  funnel as (
    select jsonb_build_object(
      'board_views',count(*) filter(where event_name='page_view' and page_path in ('/index.html','/board.html')),
      'match_opens',count(*) filter(where event_name='match_opened'),
      'records_added',count(*) filter(where event_name in ('slip_added','record_saved')),
      'shares_completed',count(*) filter(where event_name='share_completed'),
      'community_posts',count(*) filter(where event_name='community_posted')
    ) value from base
  )
  select jsonb_build_object(
    'version','v186',
    'days',clean_days,
    'sessions',s.sessions,
    'page_views',s.page_views,
    'interactions',s.interactions,
    'engagement_rate',round(100.0*s.engaged_sessions/nullif(s.sessions,0),1),
    'client_errors',s.client_errors,
    'push_enabled',s.push_enabled,
    'top_pages',p.value,
    'top_events',e.value,
    'top_entities',t.value,
    'daily',d.value,
    'device_mix',dm.value,
    'vitals',v.value,
    'funnel',f.value
  ) into result
  from session_stats s,top_pages p,top_events e,top_entities t,daily d,device_mix dm,vitals v,funnel f;

  return coalesce(result,'{}'::jsonb);
end;
$$;

revoke all on function public.p2u_admin_analytics_overview(integer) from public;
grant execute on function public.p2u_admin_analytics_overview(integer) to authenticated;

create or replace function public.p2u_admin_analytics_purge(p_before timestamptz)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare deleted_count integer;
begin
  if not public.p2u_has_admin_role(array['owner','admin']) then
    raise exception 'Admin role required' using errcode='42501';
  end if;
  if p_before is null or p_before > now() - interval '90 days' then
    raise exception 'Retention cutoff must be at least 90 days old' using errcode='22023';
  end if;
  delete from public.p2u_analytics_events where occurred_at < p_before;
  get diagnostics deleted_count = row_count;
  return jsonb_build_object('ok',true,'deleted',deleted_count,'before',p_before,'version','v186');
end;
$$;

revoke all on function public.p2u_admin_analytics_purge(timestamptz) from public;
grant execute on function public.p2u_admin_analytics_purge(timestamptz) to authenticated;

commit;
