-- Predict2U v183 — Real Push Notifications
-- Run AFTER v180 Accounts and v181 Backend Admin in the same Supabase project.
-- Browser clients use only the publishable key. VAPID private keys and service-role
-- credentials belong in Supabase Edge Function secrets, never in public files.

begin;

create table if not exists public.p2u_push_public_config (
  id text primary key default 'global',
  enabled boolean not null default false,
  vapid_public_key text not null default '',
  provider text not null default 'web-push',
  updated_at timestamptz not null default now(),
  updated_by uuid null references auth.users(id) on delete set null
);
insert into public.p2u_push_public_config(id) values ('global') on conflict (id) do nothing;
alter table public.p2u_push_public_config enable row level security;
drop policy if exists "Public reads push configuration" on public.p2u_push_public_config;
create policy "Public reads push configuration" on public.p2u_push_public_config
for select to anon, authenticated using (id='global');

create table if not exists public.p2u_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  device_label text not null default 'Browser',
  user_agent text not null default '',
  enabled boolean not null default true,
  failure_count integer not null default 0,
  last_error text not null default '',
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists p2u_push_subscriptions_user_idx on public.p2u_push_subscriptions(user_id,enabled);
create index if not exists p2u_push_subscriptions_seen_idx on public.p2u_push_subscriptions(last_seen_at desc);
alter table public.p2u_push_subscriptions enable row level security;
drop policy if exists "Users read own push subscriptions" on public.p2u_push_subscriptions;
create policy "Users read own push subscriptions" on public.p2u_push_subscriptions
for select to authenticated using (auth.uid()=user_id);
drop policy if exists "Users delete own push subscriptions" on public.p2u_push_subscriptions;
create policy "Users delete own push subscriptions" on public.p2u_push_subscriptions
for delete to authenticated using (auth.uid()=user_id);

create table if not exists public.p2u_push_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  enabled boolean not null default true,
  board_updates boolean not null default true,
  match_status boolean not null default true,
  favorite_leagues boolean not null default true,
  favorite_engines boolean not null default true,
  community_wins boolean not null default true,
  followed_users boolean not null default false,
  announcements boolean not null default true,
  verified_only boolean not null default false,
  quiet_enabled boolean not null default false,
  quiet_start time not null default '22:00',
  quiet_end time not null default '07:00',
  timezone text not null default 'UTC',
  timezone_offset_minutes integer not null default 0 check (timezone_offset_minutes between -840 and 840),
  favorite_league_names text[] not null default '{}',
  favorite_engine_names text[] not null default '{}',
  followed_user_ids uuid[] not null default '{}',
  updated_at timestamptz not null default now()
);
alter table public.p2u_push_preferences enable row level security;
drop policy if exists "Users read own push preferences" on public.p2u_push_preferences;
create policy "Users read own push preferences" on public.p2u_push_preferences
for select to authenticated using (auth.uid()=user_id);

create table if not exists public.p2u_push_jobs (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('board','match','community','announcement','system','test')),
  title text not null,
  body text not null default '',
  url text not null default 'index.html',
  audience jsonb not null default '{"type":"all"}'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','processing','completed','failed','cancelled')),
  requested_by uuid null references auth.users(id) on delete set null,
  scheduled_for timestamptz not null default now(),
  started_at timestamptz null,
  completed_at timestamptz null,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  skipped_count integer not null default 0,
  error text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists p2u_push_jobs_dispatch_idx on public.p2u_push_jobs(status,scheduled_for,id);
create index if not exists p2u_push_jobs_created_idx on public.p2u_push_jobs(created_at desc);
alter table public.p2u_push_jobs enable row level security;
drop policy if exists "Admins read push jobs" on public.p2u_push_jobs;
create policy "Admins read push jobs" on public.p2u_push_jobs
for select to authenticated using (public.p2u_has_admin_role(array['owner','admin','moderator']));

create table if not exists public.p2u_push_delivery_log (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.p2u_push_jobs(id) on delete cascade,
  subscription_id bigint null references public.p2u_push_subscriptions(id) on delete set null,
  user_id uuid null references auth.users(id) on delete set null,
  status text not null check (status in ('sent','failed','skipped')),
  response_code integer null,
  error text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists p2u_push_delivery_job_idx on public.p2u_push_delivery_log(job_id,created_at desc);
create index if not exists p2u_push_delivery_user_idx on public.p2u_push_delivery_log(user_id,created_at desc);
alter table public.p2u_push_delivery_log enable row level security;
drop policy if exists "Admins read push deliveries" on public.p2u_push_delivery_log;
create policy "Admins read push deliveries" on public.p2u_push_delivery_log
for select to authenticated using (public.p2u_has_admin_role(array['owner','admin','moderator']));
drop policy if exists "Users read own push deliveries" on public.p2u_push_delivery_log;
create policy "Users read own push deliveries" on public.p2u_push_delivery_log
for select to authenticated using (auth.uid()=user_id);
drop policy if exists "Users read delivered push jobs" on public.p2u_push_jobs;
create policy "Users read delivered push jobs" on public.p2u_push_jobs
for select to authenticated using (
  exists(select 1 from public.p2u_push_delivery_log l where l.job_id=p2u_push_jobs.id and l.user_id=auth.uid())
);

create or replace function public.p2u_register_push_subscription(
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_device_label text default 'Browser',
  p_user_agent text default ''
) returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare row_out public.p2u_push_subscriptions%rowtype;
begin
  if auth.uid() is null then raise exception 'Sign in required' using errcode='42501'; end if;
  if length(trim(coalesce(p_endpoint,'')))<20 then raise exception 'Invalid push endpoint'; end if;
  if length(trim(coalesce(p_p256dh,'')))<20 or length(trim(coalesce(p_auth,'')))<8 then raise exception 'Invalid push keys'; end if;
  insert into public.p2u_push_subscriptions(user_id,endpoint,p256dh,auth,device_label,user_agent,enabled,last_seen_at,updated_at)
  values(auth.uid(),left(trim(p_endpoint),2000),left(trim(p_p256dh),500),left(trim(p_auth),500),left(trim(coalesce(p_device_label,'Browser')),80),left(trim(coalesce(p_user_agent,'')),500),true,now(),now())
  on conflict(endpoint) do update set
    user_id=auth.uid(),p256dh=excluded.p256dh,auth=excluded.auth,device_label=excluded.device_label,
    user_agent=excluded.user_agent,enabled=true,failure_count=0,last_error='',last_seen_at=now(),updated_at=now()
  returning * into row_out;
  return jsonb_build_object('id',row_out.id,'enabled',row_out.enabled,'device_label',row_out.device_label,'updated_at',row_out.updated_at);
end;
$$;
revoke all on function public.p2u_register_push_subscription(text,text,text,text,text) from public;
grant execute on function public.p2u_register_push_subscription(text,text,text,text,text) to authenticated;

create or replace function public.p2u_unregister_push_subscription(p_endpoint text)
returns boolean
language plpgsql
security definer
set search_path=public,auth
as $$
declare changed integer;
begin
  if auth.uid() is null then raise exception 'Sign in required' using errcode='42501'; end if;
  update public.p2u_push_subscriptions set enabled=false,updated_at=now()
  where user_id=auth.uid() and endpoint=trim(coalesce(p_endpoint,''));
  get diagnostics changed=row_count;
  return changed>0;
end;
$$;
revoke all on function public.p2u_unregister_push_subscription(text) from public;
grant execute on function public.p2u_unregister_push_subscription(text) to authenticated;

create or replace function public.p2u_save_push_preferences(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare row_out public.p2u_push_preferences%rowtype;
begin
  if auth.uid() is null then raise exception 'Sign in required' using errcode='42501'; end if;
  insert into public.p2u_push_preferences(
    user_id,enabled,board_updates,match_status,favorite_leagues,favorite_engines,community_wins,
    followed_users,announcements,verified_only,quiet_enabled,quiet_start,quiet_end,timezone,
    timezone_offset_minutes,favorite_league_names,favorite_engine_names,followed_user_ids,updated_at
  ) values (
    auth.uid(),
    coalesce((p_payload->>'enabled')::boolean,true),
    coalesce((p_payload->>'board_updates')::boolean,true),
    coalesce((p_payload->>'match_status')::boolean,true),
    coalesce((p_payload->>'favorite_leagues')::boolean,true),
    coalesce((p_payload->>'favorite_engines')::boolean,true),
    coalesce((p_payload->>'community_wins')::boolean,true),
    coalesce((p_payload->>'followed_users')::boolean,false),
    coalesce((p_payload->>'announcements')::boolean,true),
    coalesce((p_payload->>'verified_only')::boolean,false),
    coalesce((p_payload->>'quiet_enabled')::boolean,false),
    coalesce(nullif(p_payload->>'quiet_start','')::time,'22:00'::time),
    coalesce(nullif(p_payload->>'quiet_end','')::time,'07:00'::time),
    left(coalesce(nullif(p_payload->>'timezone',''),'UTC'),80),
    greatest(-840,least(840,coalesce((p_payload->>'timezone_offset_minutes')::integer,0))),
    coalesce((select array_agg(left(value,120)) from (select value from jsonb_array_elements_text(coalesce(p_payload->'favorite_league_names','[]'::jsonb)) limit 80) x),'{}'::text[]),
    coalesce((select array_agg(left(value,80)) from (select value from jsonb_array_elements_text(coalesce(p_payload->'favorite_engine_names','[]'::jsonb)) limit 40) x),'{}'::text[]),
    coalesce((select array_agg(value::uuid) from (select value from jsonb_array_elements_text(coalesce(p_payload->'followed_user_ids','[]'::jsonb)) where value ~* '^[0-9a-f-]{36}$' limit 500) x),'{}'::uuid[]),
    now()
  )
  on conflict(user_id) do update set
    enabled=excluded.enabled,board_updates=excluded.board_updates,match_status=excluded.match_status,
    favorite_leagues=excluded.favorite_leagues,favorite_engines=excluded.favorite_engines,
    community_wins=excluded.community_wins,followed_users=excluded.followed_users,
    announcements=excluded.announcements,verified_only=excluded.verified_only,
    quiet_enabled=excluded.quiet_enabled,quiet_start=excluded.quiet_start,quiet_end=excluded.quiet_end,
    timezone=excluded.timezone,timezone_offset_minutes=excluded.timezone_offset_minutes,
    favorite_league_names=excluded.favorite_league_names,favorite_engine_names=excluded.favorite_engine_names,
    followed_user_ids=excluded.followed_user_ids,updated_at=now()
  returning * into row_out;
  return to_jsonb(row_out);
end;
$$;
revoke all on function public.p2u_save_push_preferences(jsonb) from public;
grant execute on function public.p2u_save_push_preferences(jsonb) to authenticated;

create or replace function public.p2u_admin_push_metrics()
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
begin
  if not public.p2u_has_admin_role(array['owner','admin','moderator']) then
    raise exception 'Admin role required' using errcode='42501';
  end if;
  return jsonb_build_object(
    'active_devices',(select count(*) from public.p2u_push_subscriptions where enabled=true),
    'pending_jobs',(select count(*) from public.p2u_push_jobs where status='pending'),
    'sent_total',(select coalesce(sum(sent_count),0) from public.p2u_push_jobs),
    'failed_total',(select coalesce(sum(failed_count),0) from public.p2u_push_jobs),
    'last_dispatch',(select max(completed_at) from public.p2u_push_jobs where completed_at is not null)
  );
end;
$$;
revoke all on function public.p2u_admin_push_metrics() from public;
grant execute on function public.p2u_admin_push_metrics() to authenticated;

create or replace function public.p2u_admin_set_push_public_key(p_public_key text,p_enabled boolean default true)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare row_out public.p2u_push_public_config%rowtype;
begin
  if not public.p2u_has_admin_role(array['owner']) then raise exception 'Owner role required' using errcode='42501'; end if;
  if p_enabled and length(trim(coalesce(p_public_key,'')))<60 then raise exception 'A valid VAPID public key is required'; end if;
  update public.p2u_push_public_config set vapid_public_key=trim(coalesce(p_public_key,'')),enabled=coalesce(p_enabled,false),updated_at=now(),updated_by=auth.uid()
  where id='global' returning * into row_out;
  perform public.p2u_write_admin_audit('push.config','push_config','global',null,to_jsonb(row_out),'{}'::jsonb);
  return to_jsonb(row_out);
end;
$$;
revoke all on function public.p2u_admin_set_push_public_key(text,boolean) from public;
grant execute on function public.p2u_admin_set_push_public_key(text,boolean) to authenticated;

create or replace function public.p2u_admin_queue_push(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public,auth
as $$
declare row_out public.p2u_push_jobs%rowtype;
declare clean_category text:=lower(trim(coalesce(p_payload->>'category','system')));
begin
  if not public.p2u_has_admin_role(array['owner','admin']) then raise exception 'Admin role required' using errcode='42501'; end if;
  if clean_category not in ('board','match','community','announcement','system','test') then raise exception 'Invalid push category'; end if;
  if trim(coalesce(p_payload->>'title',''))='' then raise exception 'Notification title is required'; end if;
  insert into public.p2u_push_jobs(category,title,body,url,audience,payload,requested_by,scheduled_for)
  values(
    clean_category,
    left(trim(p_payload->>'title'),100),
    left(trim(coalesce(p_payload->>'body','')),240),
    left(trim(coalesce(nullif(p_payload->>'url',''),'index.html')),500),
    coalesce(p_payload->'audience','{"type":"all"}'::jsonb),
    coalesce(p_payload->'payload','{}'::jsonb),
    auth.uid(),
    coalesce(nullif(p_payload->>'scheduled_for','')::timestamptz,now())
  ) returning * into row_out;
  perform public.p2u_write_admin_audit('push.queue','push_job',row_out.id::text,null,to_jsonb(row_out),'{}'::jsonb);
  return to_jsonb(row_out);
end;
$$;
revoke all on function public.p2u_admin_queue_push(jsonb) from public;
grant execute on function public.p2u_admin_queue_push(jsonb) to authenticated;

create or replace function public.p2u_claim_push_jobs(p_limit integer default 10)
returns setof public.p2u_push_jobs
language plpgsql
security definer
set search_path=public
as $$
begin
  return query
  with claimed as (
    select id from public.p2u_push_jobs
    where status='pending' and scheduled_for<=now()
    order by scheduled_for,id
    for update skip locked
    limit greatest(1,least(coalesce(p_limit,10),50))
  )
  update public.p2u_push_jobs j set status='processing',started_at=now(),error=''
  from claimed c where j.id=c.id
  returning j.*;
end;
$$;
revoke all on function public.p2u_claim_push_jobs(integer) from public;
grant execute on function public.p2u_claim_push_jobs(integer) to service_role;

create or replace function public.p2u_finish_push_job(
  p_job_id bigint,p_status text,p_sent integer,p_failed integer,p_skipped integer,p_error text default ''
) returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  update public.p2u_push_jobs set
    status=case when p_status in ('completed','failed','cancelled') then p_status else 'failed' end,
    sent_count=greatest(0,coalesce(p_sent,0)),failed_count=greatest(0,coalesce(p_failed,0)),
    skipped_count=greatest(0,coalesce(p_skipped,0)),error=left(coalesce(p_error,''),1000),completed_at=now()
  where id=p_job_id;
end;
$$;
revoke all on function public.p2u_finish_push_job(bigint,text,integer,integer,integer,text) from public;
grant execute on function public.p2u_finish_push_job(bigint,text,integer,integer,integer,text) to service_role;

create or replace function public.p2u_push_from_site_settings()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if old.board_published=false and new.board_published=true then
    insert into public.p2u_push_jobs(category,title,body,url,audience,payload,requested_by)
    values('board','Today''s Predict2U board is live','The latest board has been published.','index.html','{"type":"all"}'::jsonb,'{"source":"site_settings"}'::jsonb,new.updated_by);
  end if;
  if new.announcement_enabled=true and (
    old.announcement_enabled is distinct from new.announcement_enabled or
    old.announcement_message is distinct from new.announcement_message
  ) and trim(new.announcement_message)<>'' then
    insert into public.p2u_push_jobs(category,title,body,url,audience,payload,requested_by)
    values('announcement','Predict2U update',left(new.announcement_message,240),coalesce(nullif(new.announcement_link_url,''),'index.html'),'{"type":"all"}'::jsonb,jsonb_build_object('tone',new.announcement_tone),new.updated_by);
  end if;
  return new;
end;
$$;
drop trigger if exists p2u_push_site_settings_trigger on public.p2u_site_settings;
create trigger p2u_push_site_settings_trigger
after update on public.p2u_site_settings
for each row execute function public.p2u_push_from_site_settings();

create or replace function public.p2u_push_from_community_moderation()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if new.status='verified' and (tg_op='INSERT' or old.status is distinct from new.status) then
    insert into public.p2u_push_jobs(category,title,body,url,audience,payload,requested_by)
    values('community','Community record verified','A Community record has been reviewed and verified.','community.html',
      '{"type":"community"}'::jsonb,jsonb_build_object('slip_id',new.slip_id,'verified',true),new.updated_by);
  end if;
  return new;
end;
$$;
drop trigger if exists p2u_push_community_trigger on public.p2u_community_moderation;
create trigger p2u_push_community_trigger
after insert or update on public.p2u_community_moderation
for each row execute function public.p2u_push_from_community_moderation();


-- Optional automatic followed-user posts. This trigger is installed only when
-- the existing public.slips table is present.
create or replace function public.p2u_push_from_public_slip()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare payload jsonb:=to_jsonb(new);
declare author_id uuid;
declare handle text;
declare public_post boolean;
begin
  public_post:=lower(coalesce(payload->>'is_public','false')) in ('true','t','1','yes');
  begin author_id:=nullif(payload->>'user_id','')::uuid; exception when others then author_id:=null; end;
  handle:=left(coalesce(nullif(payload->>'handle',''),nullif(payload->>'user_handle',''),'Community member'),50);
  if public_post and author_id is not null then
    insert into public.p2u_push_jobs(category,title,body,url,audience,payload,requested_by)
    values('community',handle||' posted a Community record','A member you follow shared a new public record.','community.html',
      jsonb_build_object('type','followed_user','author_user_id',author_id::text),
      jsonb_build_object('source','slips','slip_id',coalesce(payload->>'id',''),'author_user_id',author_id::text),author_id);
  end if;
  return new;
end;
$$;

do $$
begin
  if to_regclass('public.slips') is not null then
    execute 'drop trigger if exists p2u_push_public_slip_trigger on public.slips';
    execute 'create trigger p2u_push_public_slip_trigger after insert on public.slips for each row execute function public.p2u_push_from_public_slip()';
  end if;
end $$;

commit;
