-- Predict2U v180 — Accounts, Cloud Sync & Follow System
-- Run this once in Supabase SQL Editor for the SAME project used by community.js.
-- The browser uses only the public publishable key. RLS below protects user data.

create table if not exists public.p2u_cloud_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  preferences jsonb not null default '{}'::jsonb,
  alert_settings jsonb not null default '{}'::jsonb,
  draft_slip jsonb not null default '{"legs":[],"stake":1}'::jsonb,
  client_version text not null default 'v180',
  updated_at timestamptz not null default now()
);

alter table public.p2u_cloud_state enable row level security;
drop policy if exists "Users read own cloud state" on public.p2u_cloud_state;
create policy "Users read own cloud state" on public.p2u_cloud_state for select using (auth.uid() = user_id);
drop policy if exists "Users insert own cloud state" on public.p2u_cloud_state;
create policy "Users insert own cloud state" on public.p2u_cloud_state for insert with check (auth.uid() = user_id);
drop policy if exists "Users update own cloud state" on public.p2u_cloud_state;
create policy "Users update own cloud state" on public.p2u_cloud_state for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users delete own cloud state" on public.p2u_cloud_state;
create policy "Users delete own cloud state" on public.p2u_cloud_state for delete using (auth.uid() = user_id);

create table if not exists public.p2u_follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  target_key text not null,
  target_user_id uuid null references auth.users(id) on delete cascade,
  target_handle text null,
  created_at timestamptz not null default now(),
  primary key (follower_id,target_key),
  constraint p2u_follow_not_self check (target_user_id is null or follower_id <> target_user_id)
);
create index if not exists p2u_follows_target_user_idx on public.p2u_follows(target_user_id);
create index if not exists p2u_follows_target_handle_idx on public.p2u_follows(lower(target_handle));
alter table public.p2u_follows enable row level security;
drop policy if exists "Users read follows" on public.p2u_follows;
create policy "Users read follows" on public.p2u_follows for select using (auth.role() = 'authenticated');
drop policy if exists "Users create own follows" on public.p2u_follows;
create policy "Users create own follows" on public.p2u_follows for insert with check (auth.uid() = follower_id);
drop policy if exists "Users remove own follows" on public.p2u_follows;
create policy "Users remove own follows" on public.p2u_follows for delete using (auth.uid() = follower_id);

create table if not exists public.p2u_account_deletion_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text null,
  requested_at timestamptz not null default now(),
  status text not null default 'pending' check (status in ('pending','processing','completed','cancelled')),
  completed_at timestamptz null
);
alter table public.p2u_account_deletion_requests enable row level security;
drop policy if exists "Users submit deletion request" on public.p2u_account_deletion_requests;
create policy "Users submit deletion request" on public.p2u_account_deletion_requests for insert with check (auth.uid() = user_id);
drop policy if exists "Users read deletion request" on public.p2u_account_deletion_requests;
create policy "Users read deletion request" on public.p2u_account_deletion_requests for select using (auth.uid() = user_id);

-- Optional: automatically refresh updated_at during direct database updates.
create or replace function public.p2u_touch_updated_at() returns trigger language plpgsql security invoker as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists p2u_cloud_state_touch on public.p2u_cloud_state;
create trigger p2u_cloud_state_touch before update on public.p2u_cloud_state for each row execute function public.p2u_touch_updated_at();
